### ISSUE TITLE
Accept ...core#resource as mixin's implies

### ISSUE THREAD

**Issue by jeanparpaillon** [erocci/erocci#12]
Mixin 'applies' attributes should allow ...core#resource and ...core#link

**Comment by philippemerle** [comment]
This bug is not urgent to resolve.
Currently Cloud Designer already deals with it.

**Comment by jeanparpaillon** [comment]
Should be fixed in https://github.com/erocci/erocci/commit/ccdcf95dddf53e4d437193adffc0dfbb38969e68

Can you check ?
