### ISSUE TITLE
http: HEAD command not supported

### ISSUE THREAD

**Issue by jeanparpaillon** [erocci/erocci#13]
HEAD command on /-/ interface returns 500

**Comment by philippemerle** [comment]
Supporting HEAD on /-/ is a first step to have interoperability from jOCCI to erocci.
Implementing this feature is required for implementing the jOCCI connector of the OCCIware Cloud Designer.
Potentially Roboconf would use jOCCI to send OCCI requests to ProActive Cloud Automation.
Other OCCIware backends could also use jOCCI to interact with other OCCIware backends.

**Comment by philippemerle** [comment]
After patching jOCCI to avoid to send the HEAD request then new problems appear!
jOCCI throws an exception when it tries to parse OCCI server requests.
More investigations are required to understand what jOCCI expects.
So resolving this HEAD issue is not so urgent.

**Comment by jeanparpaillon** [comment]
HEAD command is used by every REST library

Fixed in https://github.com/erocci/erocci_listener_http/commit/18058b2082658b231de14faf3faac0ab96f4076f
