### ISSUE TITLE
Category 'entity' has no parent

### ISSUE THREAD

**Issue by philippemerle** [erocci/erocci#24]
Let start an erocci server then introspect it:
$ curl $EROCCI_URL/-/
category: link; scheme="http://schemas.ogf.org/occi/core#"; class="kind"; title="Core Link"; rel="http://schemas.ogf.org/occi/core#entity"; location="/collections/link/"
category: resource; scheme="http://schemas.ogf.org/occi/core#"; class="kind"; title="Core Resource"; rel="http://schemas.ogf.org/occi/core#entity"; location="/collections/resource/"; attributes="occi.core.summary"
category: entity; scheme="http://schemas.ogf.org/occi/core#"; class="kind"; title="Core Entity"; rel="http://schemas.ogf.org/occi/core#root"; location="/collections/entity/"; attributes="occi.core.title occi.core.id"
...

erocci returns that category 'entity' has category 'root' as parent.
But category 'entity' is the root of the OCCI type system and has no parent.
erocci must reply:
...
category: entity; scheme="http://schemas.ogf.org/occi/core#"; class="kind"; title="Core Entity"; location="/collections/entity/"; attributes="occi.core.title occi.core.id"
...

**Comment by jeanparpaillon** [comment]
Fixed in https://github.com/erocci/erocci_core/commit/bffc5d949375de5869105ff55a2ff973fc178e49
