### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by philippemerle** [erocci/erocci#25]
Let start an erocci server with the OCCI Infrastructure Extension.
Then let create a compute:
$ curl -X PUT $EROCCI_URL/compute/vm1 -H 'Content-Type: text/occi' -H 'Category: compute; scheme="http://schemas.ogf.org/occi/infrastructure#"; class="kind";' -H 'X-OCCI-Attribute: occi.compute.hostname="vm1"' -H 'X-OCCI-Attribute: occi.compute.architecture="x64"' -H 'X-OCCI-Attribute: occi.compute.cores=4' -H 'X-OCCI-Attribute: occi.compute.memory=4'

Then retrieve it:
$ curl -i $EROCCI_URL/compute/vm1
HTTP/1.1 500 Internal Server Error
connection: keep-alive
date: Mon, 30 Nov 2015 10:13:58 GMT
content-length: 0
server: erocci OCCI/1.1
content-type: text/plain
vary: accept

The erocci logs is attached following.
[erocci.txt](https://github.com/erocci/erocci/files/47155/erocci.txt)

**Comment by jeanparpaillon** [comment]
Fixed in https://github.com/erocci/erocci_core/commit/567d28b681e9b5c7ef00f8554afdf5f6f525b513
