### ISSUE TITLE
text rendering of mixins with applies

### ISSUE THREAD

**Issue by philippemerle** [erocci/erocci#30]
Let start an erocci server with the OCCI infrastructure extension and introspect it:
$ curl $EROCCI_URL/-/
...
category: os_tpl; scheme="http://schemas.ogf.org/occi/infrastructure#"; class="mixin"; title="OS Template"; rel="http://schemas.ogf.org/occi/infrastructure#compute"; location="/collections/os_tpl/"
...
Let note that the 'rel' of 'os_tpl' is "...#compute"

With rOCCI:
$ curl http://rocci-server-1-1-x.herokuapp.com/-/
...
Category: os_tpl;scheme="http://schemas.ogf.org/occi/infrastructure#";class="mixin";title="operating system template";location="/mixin/os_tpl/"
...
Let note that 'os_tpl' has no 'rel' .

The jOCCI library requires that if any the 'rel' of a mixin must be a mixin (not a king).
Then jOCCI can not interoperate with erocci.

Suggestion: erocci should only return 'depends' of mixin and not 'applies' of the mixin.

**Comment by jeanparpaillon** [comment]
A valid description of infrastructure extension can be found here:
https://github.com/erocci/erocci_backend_mnesia/blob/master/priv/occi-infrastructure.xml

BTW, we should find a way to centralize extensions

If jOCCI considers 'rel' of a mixin must be a mixin, it is an error. While the spec is not clear on that, any type of relation can be displayed (parent, depends, applies)

**Comment by philippemerle** [comment]
In GFD.183 page 9 table 3, Mixins.related is defined as "the set of related Mixin instances".
In GFD.185 end of page 8, this is a rendering example of a mixin which is related to another mixin.
So jOCCI considering 'rel' of a mixin must be a mixin, it is correct.
However the GFD.185 spec could be more explicit on the example of page 8.
In GFD.183 and 185, there are no notions of parent, depends, applies only the notion of related.
So which specs are implemented by erocci?

**Comment by jeanparpaillon** [comment]
In version 1.0, the Core spec only had 'rel' notion. 
In version 1.1, the Core spec has been refined and the 'rel' notion is now splitted in 3: parent (for kind), applies and depends (for mixins).
The Text rendering spec has not been updated to reflect this change and the 'rel' keyword of the text rendering must render all these relations.

IMO, jOCCI is too restrictive when not allowing 'rel' to point a relation like 'applies' or 'parent'.

Discussion on 'rel' keyword already happens here: https://github.com/CESNET/pOCCI/issues/6 

I suppose jOCCI team would be ok to update jOCCI with regard to this interpretation of the spec.
