### ISSUE TITLE
rendering text - missing occi.core.source and occi.core.target

### ISSUE THREAD

**Issue by philippemerle** [erocci/erocci#35]
Both attributes occi.core.source and occi.core.target are missed when rendering a link:
$ curl http://192.168.99.100:8080/storagelink/sl1
category: storagelink; scheme="http://schemas.ogf.org/occi/infrastructure#"; class="kind"
x-occi-attribute: occi.storagelink.mountpoint="/mnt/scratch"
x-occi-attribute: occi.storagelink.deviceid="nfs:..."
x-occi-attribute: occi.core.id=7880112

Attribute occi.core.target is missed when rendering a resource:
$ curl http://192.168.99.100:8080/storage/storage1
category: storage; scheme="http://schemas.ogf.org/occi/infrastructure#"; class="kind"
link: <http://192.168.99.100:8080/storage/storage1>; category="http://schemas.ogf.org/occi/infrastructure#storagelink"; occi.storagelink.mountpoint="/mnt/scratch"; occi.storagelink.deviceid="nfs:..."; occi.core.id=5934822
link: <http://192.168.99.100:8080/storage/storage1>; category="http://schemas.ogf.org/occi/infrastructure#storagelink"; occi.storagelink.mountpoint="/mnt/scratch"; occi.storagelink.deviceid="nfs:..."; occi.core.id=7880112
x-occi-attribute: occi.storage.size=100000.000000
x-occi-attribute: occi.core.id=107526770

**Comment by jeanparpaillon** [comment]
Ok for rendering a link. When rendering a resource, source is the uri of the resource and target is the uri between '<' and '>'. Let me ask for confirmation on occi-wg mailing list.

Should be closed in https://github.com/erocci/erocci_core/commit/399e4c580ec23bda55abffd364b56ba895a7059d
