### ISSUE TITLE
dbus backend: should handle multiple schemas

### ISSUE THREAD

**Issue by jeanparpaillon** [erocci/erocci#36]
Contrary to erlang API, DBus API allows only one schema to be provided.

**Comment by mdutoo** [comment]
And most use cases require more than one. Even most IaaS provider will need, in addition to the occi-infrastructure schema, an additional schema that define their implementation- and provider-specific properties.

**Comment by cgourdin** [comment]
I'm totally blocked with that, i need infrastructure schema and docker schema to use erocci with erocci-dbus-java and docker connector, i don't know how to set the two schemas.

**Comment by jeanparpaillon** [comment]
Hi,
For the moment, I suggest you put all your kinds/mixins in a single <extension /> element.
<extension ...>
 <kind... />
 <kind.../>
  <mixin .../>
 ...
</extension>

Tell me if this is feasible for you.

**Comment by cgourdin** [comment]
Hello,
Do you suggest me to merge infrastructure schema and docker schema in one schema ?

**Comment by jeanparpaillon** [comment]
I would prefer yes. I am accumulating some changes to do in the D-Bus API (serial number, multiple schemas, filtering, etc) but I would prefer upgrade all in once, if possible.

**Comment by cgourdin** [comment]
ok, i'll try that.

**Comment by cgourdin** [comment]
For finding a workaround, I had merge core and infrastructure schema for my tests (core.xml on erocci/deps/erocci_core/priv/schemas/occi-core.xml), for compute infrastructure resource it works as expected, but when i add the schema docker (via dbus method Get() ), and want to save a docker machine (extends from infrastructure compute scheme), it doesn't work at all. SaveResource() method is never called. Find(id) method is called as usual.

I dont know how to read the Erocci log trace to understand what's going wrong here.

The following zip has the schemas and Erocci logs i obtain. 
Thank you for your response.
[test_erocci_docker.zip](https://github.com/erocci/erocci/files/184239/test_erocci_docker.zip)

**Comment by jeanparpaillon** [comment]
Hi, your docker schema is not correct: authorized 'parent' value for a Kind is "resource" or "link". This should not be allowed by OCCIware Studio.

**Comment by philippemerle** [comment]
Where is written in the OCCI core specification that authorized 'parent' value for a Kind is "resource" or "link"?

**Comment by jeanparpaillon** [comment]
As of today, OCCI Core does not specify a generic semantic for parent relation. it is only specified for resource and links. I can understand it could be interested to have a generic semantic, but this would require declinations in API / renderings.

If someone is interested in having a general semantic for 'parent' relation, this discussion should be moved to occi-wg, not at runtime implementation level.

**Comment by philippemerle** [comment]
Please read the OCCI core 1.2 specification section 5.3.3.
in Table 4: "parent Kind 0..1 Immutable Another Kind instance which this Kind has an inheritance
relationship with." **-> parent relationship = inheritance relationship**
around Line 223: "If type B inherits type A, where A is a sub-type of Entity, the Kind instance of B MUST have its parent attribute set to the Kind instance of A" -> **nothing here avoid B has parent = A which has parent = resource which has parent = entity**
Nothing in OCCI limits a kind inheritance graph to 3 levels (entity, resource/link, user definer kinds).

**Comment by jeanparpaillon** [comment]
Indeed, thanks for pointing it.
This behaviour is implemented in new Core model implementation which will be soon merged into erocci: https://github.com/erocci/erlang-occi 
Will close when merged.
