### ISSUE TITLE
More readable logging

### ISSUE THREAD

**Issue by mdutoo** [erocci/erocci#37]
ex. line by line, so that it becomes more compact and readable.

**Comment by jeanparpaillon** [comment]
erocci uses standard erlang/OTP logging. 
See http://erlang.org/doc/system_principles/error_logging.html for how to use it

**Comment by mdutoo** [comment]
Well, I only opened this one because we had talked about it together in December workshops and it looked to me like you could do something about it...

**Comment by jeanparpaillon** [comment]
Improving logging readability is always a good idea, but it is too vague as an issue.
Eventually, I would prefer to reopen several issues on specific, small, fixable objectives: document logging, move this message to debug instead of info, etc

**Comment by mdutoo** [comment]
OK, got it.
