### ISSUE TITLE
backend: (also) delegate version check to backend

### ISSUE THREAD

**Issue by mdutoo** [erocci/erocci#38]
(seen in December workshop)

For now, erocci doesn't provide version to backends. But it should, because it can't always check it itself, if only because it aims to be compatible with a models@runtime architecture, where by essence backend runtimes are able to modify OCCI data without erocci knowing, but also because of other use cases:
- allowing the backend to use the version along with its optimistic locking-capable data store (ex. MongoDB) to implement optimistic locking
- backend runtime server-side computed fields
- allowing to implement client-side caching in erocci. Though if erocci is installed on the same machine as runtime backends, it maybe adds nothing performance-wise and only complexifies the architecture of erocci. HOWEVER even then erocci should allow clients to implement version / etag-based client-side caching by implementing HTTP If-None-Match/If-Match header, see http://odino.org/don-t-rape-http-if-none-match-the-412-http-status-code/ . Probably should be extrated to another issue ?

In addition to letting backends check the version themselves, the current behaviour could be kept for ex. simple or human-powered backends, but with added erocci-side locks to ensure atomicity of backend operations.

**Comment by jeanparpaillon** [comment]
New backend API:
backend store a serial for entities, and erocci core deals with checking versions
