### ISSUE TITLE
backend: return State returned by backend rather than id, to be RESTful

### ISSUE THREAD

**Issue by mdutoo** [erocci/erocci#39]
For now, backend create/update/delete methods only returns OCCI resource Id, ex. in the SaveResource() dbus java method:
https://github.com/erocci/erocci_backend_dbus/blob/master/src/erocci_backend_dbus.erl#L69

But as a REST API server, erocci should return the whole new version of the Resource, which is not necessarily the one sent by the client, for instance: in POST, if version checked & incremented on backend side (see #38), if additional fields are computed by the backend runtime...

**Comment by jeanparpaillon** [comment]
Fixed in master branch
