### ISSUE TITLE
Removing a Mixin Definition failed

### ISSUE THREAD

**Issue by philippemerle** [erocci/erocci#46]
$ curl -i -v -X POST -H "Content-Type: text/occi" -H 'Category: my_stuff; scheme="http://example.com/occi/my_stuff#"; class="mixin"; location="/my_stuff/"' http://malmo.lizenn.net:8080/-/
The user mixin is created.

$ curl -i -v -X DELETE -H "Content-Type: text/occi" -H 'Category: my_stuff; scheme="http://example.com/occi/my_stuff#"; class="mixin' http://malmo.lizenn.net:8080/-/
→ Internal Server Error

**Comment by philippemerle** [comment]
$ curl -i -v -X DELETE -H "Content-Type: text/occi" -H 'Category: my_stuff; scheme="http://example.com/occi/my_stuff#"; class="mixin' http://malmo.lizenn.net:8082/-/
...
HTTP/1.1 500 Internal Server Error
...

**Comment by jeanparpaillon** [comment]
Fixed in 1c318b61584dc8de10b89a70d9fa863817b55bba
