### ISSUE TITLE
Get resources failed

### ISSUE THREAD

**Issue by philippemerle** [erocci/erocci#47]
$ curl -i -v http://malmo.lizenn.net:8080/collections/user
...
HTTP/1.1 500 Internal Server Error
...

Previous curl should throw error 500 but perhaps Not Found or Bad Request.

$ curl -i -v http://malmo.lizenn.net:8080/collections/user/
...
HTTP/1.1 200 OK
...
x-occi-location: http://malmo.lizenn.net:8080/collections/user/a76e6a60-a336-307e-b2bb-d69527e6936c
x-occi-location: http://malmo.lizenn.net:8080/collections/user/c610a241-4a98-315b-b5e9-45c53c491d2b

$ curl -i -v  http://malmo.lizenn.net:8080/collections/user/a76e6a60-a336-307e-b2bb-d69527e6936c
...
HTTP/1.1 404 Not Found
...

$ curl -i -v http://malmo.lizenn.net:8080/collections/user/c610a241-4a98-315b-b5e9-45c53c491d2b
...
HTTP/1.1 404 Not Found
...

Two last curl should return user resources.

**Comment by jeanparpaillon** [comment]
Fixed by https://github.com/erocci/erocci_listener_http/commit/cf9b63ab1708ae8cba2f56582b4a6c2b12f0acfc

**Comment by philippemerle** [comment]
I config that the issue is resolved.
