### ISSUE TITLE
question on creating resources

### ISSUE THREAD

**Issue by philippemerle** [erocci/erocci#49]
Should the following request work?
$ curl -i -v -X PUT http://malmo.lizenn.net:8080/collections/user/Merle -H 'Content-Type: text/occi' -H 'Category: user; scheme="http://example.org/occi/test#"; class="kind";' -H 'X-OCCI-Attribute: blog.user.name="Merle"' -H 'X-OCCI-Attribute: blog.user.email="merle@occiware.org"'
Currently HTTP/1.1 404 Not Found

**Comment by cgourdin** [comment]
I have the same problem here with latest version of Erocci, i can't create an infrastructure compute resource. Note : Erocci-dbus-java set the infrastructure 1.2 occi schema.
here's my curl query (generated with cloud designer) : 
curl -s -v -i -X PUT http://localhost:8080/compute/ab30d56e-aad7-411d-b7a6-87f100d40dcf -H 'Content-Type: text/occi' -H 'Category: compute; scheme="http://schemas.ogf.org/occi/infrastructure#"; class="kind";' -H 'X-OCCI-Attribute: occi.core.id="ab30d56e-aad7-411d-b7a6-87f100d40dcf"' -H 'X-OCCI-Attribute: occi.core.title="resource1"' -H 'X-OCCI-Attribute: occi.core.summary=""' -H 'X-OCCI-Attribute: occi.compute.architecture="x86"' -H 'X-OCCI-Attribute: occi.compute.cores=2' -H 'X-OCCI-Attribute: occi.compute.hostname="testinfra1"' -H 'X-OCCI-Attribute: occi.compute.share=no' -H 'X-OCCI-Attribute: occi.compute.speed=2' -H 'X-OCCI-Attribute: occi.compute.memory=2' -H 'X-OCCI-Attribute: occi.compute.state="inactive"' -H 'X-OCCI-Attribute: occi.compute.state.message=""'

**Comment by philippemerle** [comment]
occi.compute.share is a number not a string, so put '0' instead of 'no' as value.

**Comment by cgourdin** [comment]
I have the same result with occi.compute.share=0, i've tried other queries and all failed, all these queries worked before.

**Comment by philippemerle** [comment]
Welcome:-( I suspect that a recent commit since our last OCCIware meeting at Nantes introduced a regression.

**Comment by philippemerle** [comment]
I confirm that this issue is resolved.
