### ISSUE TITLE
Document supported attribute types

### ISSUE THREAD

**Issue by jeanparpaillon** [erocci/erocci#5]
Supported attribute types are not documented.
So far:
- integer, 
- float
- string
- anyURI
Other types are casted on string

**Comment by philippemerle** [comment]
In https://github.com/occiware/occi-schemas/blob/master/schemas/http%253A%252F%252Fschemas.ogf.org%252Focci%252Finfrastructure%2523.xml
it seems that erocci should support XML restrictions to express enumerations (lines 17-20, 29-34, ...) in XML extension descriptors.
Is erocci support XML restrictions to express enumerations? 
or do we use xs:string for enumeration types?

**Comment by jeanparpaillon** [comment]
enums are supported on 'next' branch (still broken)
On master branch, you must use 'xs:string'

**Comment by philippemerle** [comment]
But *where* are supported attribute types documented?

**Comment by jeanparpaillon** [comment]
https://github.com/occiware/occi-schemas/blob/master/schemas/occi.xsd#L95

A more complete documentation is ongoing... contributions welcome !
