### ISSUE TITLE
Adding mixins failed

### ISSUE THREAD

**Issue by philippemerle** [erocci/erocci#50]
$ curl -i -v -X POST -H "Content-Type: text/occi" -H 'Category: my_tag; scheme="http://example.com/occi/my_tag#"; class="mixin";' http://malmo.lizenn.net:8080/-/
...
HTTP/1.1 500 Internal Server Error

What is wrong?

**Comment by philippemerle** [comment]
This error seems to due to the fact that the header does not contain location="/..../".

$ curl -i -v -X POST -H "Content-Type: text/occi" -H 'Category: my_tag; scheme="http://example.com/occi/my_tag#"; class="mixin"; location="/my_tag/"' http://malmo.lizenn.net:8080/-/
...
HTTP/1.1 200 OK
...

So when the header does not contain location="/..../" then erocci should return 400 Bad Request instead of 500 Internal Server Error.

**Comment by jeanparpaillon** [comment]
Fixed in 44b674d2119b1f3223e2dfcb32b33f7a13a05e25
