### ISSUE TITLE
Execute an action on a collection of resources

### ISSUE THREAD

**Issue by philippemerle** [erocci/erocci#52]
$ curl -v -i -X POST -H 'Content-Type: text/occi' http://malmo.lizenn.net:8082/collections/compute/?action=stop -H 'Category: stop; scheme="http://schemas.ogf.org/occi/infrastructure/compute/action#"; class="action"' -H 'X-OCCI-Attribute: method="poweroff"'
...
HTTP/1.1 204 No Content
...

Shoud this request return 200 instead of 204?

**Comment by jeanparpaillon** [comment]
Yes, latest OCCI specs say it should return the full modified collection, so 200.

**Comment by philippemerle** [comment]
In GFD.185 (OCCI HTTP 1.1), page 11, section "Triggering Actions on all Instances of a Mixin or Kind", the return is 200 OK for this curl request.
