### ISSUE TITLE
Associate a resource with a mixin should return OK instead of No Content

### ISSUE THREAD

**Issue by philippemerle** [erocci/erocci#53]
Create a resource:
$ curl -i -v -X PUT http://malmo.lizenn.net:8080/collections/user/Merle -H 'Content-Type: text/occi' -H 'Category: user; scheme="http://example.org/occi/test#"; class="kind";' -H 'X-OCCI-Attribute: blog.user.name="Merle"' -H 'X-OCCI-Attribute: blog.user.email="merle@occiware.org"'
...

Associate it with a mixin:
$ curl -v -i -X POST http://malmo.lizenn.net:8080/my_stuff/ -H 'Content-Type: text/occi' -H 'X-OCCI-Location: http://malmo.lizenn.net:8080/collections/user/Merle'
...
HTTP/1.1 204 No Content
...

$ curl http://malmo.lizenn.net:8080/my_stuff/
x-occi-location: http://malmo.lizenn.net:8080/collections/user/Merle

$ curl http://malmo.lizenn.net:8080/collections/user/Merle
category: user; scheme="http://example.org/occi/test#"; class="kind"
category: my_stuff; scheme="http://example.com/occi/my_stuff#"; class="mixin"
x-occi-attribute: blog.user.name="Merle"
x-occi-attribute: blog.user.email="merle@occiware.org"
x-occi-attribute: occi.core.id=24496558

So associate a resource with a mixin works but should return OK instead of No Content.

**Comment by philippemerle** [comment]
$ curl -v -i -X PUT http://malmo.lizenn.net:8080/my_stuff/ -H 'Content-Type: text/occi' -H 'X-OCCI-Location: http://malmo.lizenn.net:8080/collections/user/Philippe'
...
HTTP/1.1 204 No Content
...

This PUT request should return OK instead of No Content.

**Comment by jeanparpaillon** [comment]
Fixed in 44b674d2119b1f3223e2dfcb32b33f7a13a05e25
