### ISSUE TITLE
Full Update of a Mixin collection does not work

### ISSUE THREAD

**Issue by philippemerle** [erocci/erocci#54]
Create a ressource :
$ curl -i -v -X PUT http://malmo.lizenn.net:8080/collections/user/Philippe -H 'Content-Type: text/occi' -H 'Category: user; scheme="http://example.org/occi/test#"; class="kind";' -H 'X-OCCI-Attribute: blog.user.name="Merle"' -H 'X-OCCI-Attribute: blog.user.email="merle@occiware.org"'

Full Update of a Mixin collection:
$ curl -v -i -X PUT http://malmo.lizenn.net:8080/my_stuff/ -H 'Content-Type: text/occi' -H 'X-OCCI-Location: http://malmo.lizenn.net:8080/collections/user/Philippe'

$ curl http://malmo.lizenn.net:8080/my_stuff/
x-occi-location: http://malmo.lizenn.net:8080/collections/user/Merle

MUST be x-occi-location: http://malmo.lizenn.net:8080/collections/user/Philippe !

$ curl http://malmo.lizenn.net:8080/collections/user/Merle
category: user; scheme="http://example.org/occi/test#"; class="kind"
category: my_stuff; scheme="http://example.com/occi/my_stuff#"; class="mixin"
x-occi-attribute: blog.user.name="Merle"
x-occi-attribute: blog.user.email="merle@occiware.org"
x-occi-attribute: occi.core.id=24496558

Must not have category : my_stuff

$ curl http://malmo.lizenn.net:8080/collections/user/Philippe
category: user; scheme="http://example.org/occi/test#"; class="kind"
x-occi-attribute: blog.user.name="Merle"
x-occi-attribute: blog.user.email="merle@occiware.org"
x-occi-attribute: occi.core.id=24496558

Must have category : my_stuff

**Comment by jeanparpaillon** [comment]
Closed in 44b674d2119b1f3223e2dfcb32b33f7a13a05e25
