### ISSUE TITLE
Deleting a resource instance 

### ISSUE THREAD

**Issue by philippemerle** [erocci/erocci#58]
$ curl -i -v -X DELETE http://malmo.lizenn.net:8080/collections/user/Merle
...
HTTP/1.1 204 No Content
...

$ curl -i -v -X DELETE http://malmo.lizenn.net:8082/collections/compute/my_first_virtual_machine
...
HTTP/1.1 204 No Content
...

These commands should return OK instead of No Content.

**Comment by jeanparpaillon** [comment]
According to HTTP upgraded spec (1.2), 204 is now a valid return status for DELETE

**Comment by philippemerle** [comment]
I agree.
