### ISSUE TITLE
Full Update of a resource instance

### ISSUE THREAD

**Issue by philippemerle** [erocci/erocci#59]
Related to https://github.com/erocci/erocci/issues/57

**Comment by philippemerle** [comment]
$ curl -i -v -X PUT http://malmo.lizenn.net:8080/collections/user/Merle -H 'Content-Type: text/occi' -H 'Category: user; scheme="http://example.org/occi/test#"; class="kind";' -H 'X-OCCI-Attribute: blog.user.name="Merle"' -H 'X-OCCI-Attribute: blog.user.email="merle@occiware.org"'
...
HTTP/1.1 201 Created
...

$ curl http://malmo.lizenn.net:8080/collections/user/Merle
category: user; scheme="http://example.org/occi/test#"; class="kind"
x-occi-attribute: blog.user.name="Merle"
x-occi-attribute: blog.user.email="merle@occiware.org"
x-occi-attribute: occi.core.id=46353464

$ curl -i -v http://malmo.lizenn.net:8080/collections/user/Merle -X PUT -H 'Content-Type: text/occi' -H 'X-OCCI-Attribute: occi.core.id=46353464' -H 'X-OCCI-Attribute: blog.user.name="Merle"' -H 'X-OCCI-Attribute: blog.user.email="merle@occiware.org"' -H 'X-OCCI-Attribute: occi.core.title="Merle"'
...
HTTP/1.1 409 Conflict
...

Why 409 Conflict is returned?

Let's note that occi.core.id is provided. I just updated attribute occi.core.title.

With updating any attributes:
$ curl -i -v http://malmo.lizenn.net:8080/collections/user/Merle -X PUT -H 'Content-Type: text/occi' -H 'X-OCCI-Attribute: occi.core.id=46353464' -H 'X-OCCI-Attribute: blog.user.name="Merle"' -H 'X-OCCI-Attribute: blog.user.email="merle@occiware.org"'
...
HTTP/1.1 409 Conflict
...

**Comment by philippemerle** [comment]
Hi Jean, could you provide me a curl command that works well in this use case?

**Comment by philippemerle** [comment]
Another example with the OCCI Infrastructure extension:

$ curl -i -v -X PUT http://malmo.lizenn.net:8082/collections/compute/compute16 -H 'Content-Type: text/occi' -H 'Category: compute; scheme="http://schemas.ogf.org/occi/infrastructure#"; class="kind";' -H 'X-OCCI-Attribute: occi.compute.cores=2' -H 'X-OCCI-Attribute: occi.compute.hostname="foobar"'
...
HTTP/1.1 201 Created
...

$ curl http://malmo.lizenn.net:8082/collections/compute/compute16
category: compute; scheme="http://schemas.ogf.org/occi/infrastructure#"; class="kind"
x-occi-attribute: occi.compute.hostname="foobar"
x-occi-attribute: occi.compute.cores=2
x-occi-attribute: occi.core.id=4788250

$ curl -i -v -X PUT -H 'Content-Type: text/occi' -H 'X-OCCI-Attribute: occi.core.id=4788250'  -H 'X-OCCI-Attribute: occi.compute.memory=4.0' http://malmo.lizenn.net:8082/collections/compute/compute16
...
HTTP/1.1 409 Conflict
...

**Comment by jeanparpaillon** [comment]
1/ When using PUT, a full resource representation must be provided: in your second request, 'kind' is missing (PUT = create or replace <> POST = update a collection or update a resource)
2/ If you want to update an existing resource, use POST
3/ occi.core.id is a string: you must quote it with '"'

**Comment by philippemerle** [comment]
As set in the title of the issue, I would like to test "Full Update of a resource instance" so I should use PUT. According to your reply, I retested:

$ curl -i -v -X PUT http://malmo.lizenn.net:8080/collections/user/Merle -H 'Content-Type: text/occi' -H 'Category: user; scheme="http://example.org/occi/test#"; class="kind";' -H 'X-OCCI-Attribute: blog.user.name="Merle"' -H 'X-OCCI-Attribute: blog.user.email="merle@occiware.org"'

The creation of a user is ok.

$ curl http://malmo.lizenn.net:8080/collections/user/Merle
category: user; scheme="http://example.org/occi/test#"; class="kind"
x-occi-attribute: blog.user.name="Merle"
x-occi-attribute: blog.user.email="merle@occiware.org"
x-occi-attribute: occi.core.id=118193746

Let's note that in the reply, occi.core.id is not quoted with '"'.
Perhaps there is a issue in the renderer.

$ curl -i -v http://malmo.lizenn.net:8080/collections/user/Merle -X PUT -H 'Content-Type: text/occi' -H 'Category: user; scheme="http://example.org/occi/test#"; class="kind";'  -H 'X-OCCI-Attribute: occi.core.id="118193746"' -H 'X-OCCI-Attribute: blog.user.name="Merle"' -H 'X-OCCI-Attribute: blog.user.email="merle@occiware.org"' -H 'X-OCCI-Attribute: occi.core.title="Merle"'

Always returns HTTP/1.1 409 Conflict, even when providing the category and quoting the occi.core.id attribute.

So this issue is always unresolved :-(
Could you reopen it or should I create a new issue (even if this is the same)?

Perhaps the OCCI server running on malmo.lizenn.net:8080 was not updated according to recent commits in erocci.

**Comment by jeanparpaillon** [comment]
The issue has been solved in master branch.
Servers are not updated yet..

**Comment by philippemerle** [comment]
Ok. Thank you to notify us when the servers will be updated.

**Comment by jeanparpaillon** [comment]
sure
