### ISSUE TITLE
Erocci backend dbus is not in dependencies.

### ISSUE THREAD

**Issue by cgourdin** [erocci/erocci#64]
Hello,

Erocci backend dbus is not in deps directory when calling make, deps.lock dont give any references to the dbus backend module.
I can't launch the dbus backend, this is maybe due to the recent updates.
I tried to make Erocci with deps.lock updated with this line but backend dbus didn't appear in deps directory : 
occi_v = v1.0rc3
erocci_core_v = v1.0rc5
erocci_listener_http_v = v1.0rc3
erocci_backend_mnesia_v = v1.0rc2
erocci_backend_dbus_v = 8e6d374
pocci_v = v1.0.0+erocci1.1.0
edown_v = 0.8

**Comment by jeanparpaillon** [comment]
erocci 0.9 contains erocci_backend_dbus with "old" API
1.0rc (and master branch) do not contain erocci_backend_dbus, which is currently under test before integration

**Comment by jeanparpaillon** [comment]
Will close the bug when integrating erocci_backend_dbus
Until then, you can use 0.9 as before

**Comment by philippemerle** [comment]
In the OCCIware project, we don't use erocci standalone but erocci with backend dbus.
When will erocci 1.0rc include erocci_backend_dbus?

**Comment by jeanparpaillon** [comment]
Fixed in https://github.com/erocci/erocci/commit/04cdcdec9a1182b8081ad47cb6cc60711fcd3c47
