### ISSUE TITLE
collections query doesn't work (erocci with dbus)

### ISSUE THREAD

**Issue by cgourdin** [erocci/erocci#65]
Hello,

I'm testing Erocci with erocci-dlbus-java (and the new dbus facade), i have a problem with collections query : 
curl -v -X GET http://localhost:8080/collections/entity/
Invoke the method **Get(String location)**

The method **Collection(..)** is never called.

Thanks.

**Comment by jeanparpaillon** [comment]
Category collections are now under:
`/categories/...`

In a general way, you should never query an OCCI endpoint without querying `/-/` first as collections urls are only defined this way.

**Comment by cgourdin** [comment]
Ok thank you.
