### ISSUE TITLE
Use github API to retrieve documentation ?

### ISSUE THREAD

**Issue by Romathonat** [erocci/erocci#74]
With the website and the documentation on github, there is a duplication of the source of truth, which means that after each update of the doc, you'll need to change it at two different places !
I suggest the following workflow, defining the github doc as the unique source of truth :
- on the website, we get the current doc.md via the github API [https://developer.github.com/v3/repos/contents/#get-contents](https://developer.github.com/v3/repos/contents/#get-contents)
- The format of the doc is markdown, so we use a angular plugin to format it correctly ( [https://github.com/btford/angular-markdown-directive](https://github.com/btford/angular-markdown-directive) maybe ?)
- We are good

Pros:
 - No duplication of code.
 - Markdown formating

Cons:
 - Depending on an external resource : github. 

I don't think it is really a problem to depend on github, because it is a very robust system, and the erocci documentation does not seem to be a critical system.

**Comment by jeanparpaillon** [comment]
I'm ok with that :)
Furthermore, github doc is generated from erlang source code so we can have very consistant doc with this approach.
Can you make a small page with angular illustrating this ?

**Comment by Romathonat** [comment]
I think I could but it would take me some time : I don't know angular Js yet.

**Comment by jeanparpaillon** [comment]
Anyway I will try do to this way, I think this is the right approach

**Comment by Romathonat** [comment]
If you choose to do that you need to know that Github restrict the call to its Api to 50 calls/hour, or 6000 calls/hour if you use authentification [https://developer.github.com/v3/#rate-limiting](https://developer.github.com/v3/#rate-limitinghttps://developer.github.com/v3/#rate-limiting). That seems enough, but if someone with bad intentions do a mini ddos, the service would be unaivalable. In prevention, you could put a cache system.

**Comment by jeanparpaillon** [comment]
Yep, got it.
As a first approach, I'm simply sync'ing generated markdown from erocci repos to erocci website.

**Comment by jeanparpaillon** [comment]
Website documentation page points to github.
Not as fancy as integrating markdown directly but it works
