### ISSUE TITLE
occi-infra.xml: delete a storageLink

### ISSUE THREAD

**Issue by Romathonat** [erocci/erocci#79]
When I delete a storage link (link between compute and storage), I can't access to /categories/storagelink, neither to /categories/storage

**Comment by Romathonat** [comment]
In order to make the issue easy to identify, I made samples so that you can test easily.
Go to [http://occinterface.herokuapp.com](http://occinterface.herokuapp.com), click on Known issues (to the left), then follow the instructions on "deleting storage link".

**Comment by jeanparpaillon** [comment]
Indeed, backend API misses the 'link' symmetric call: 'unlink' :/
