### ISSUE TITLE
POST on malmo.lizenn.net server doesn't work

### ISSUE THREAD

**Issue by mdutoo** [erocci/erocci#80]
POSTing a resource at best returns a 500 error.

Using json representation:

cat blog2new3.json
{ "kind":"http://example.org/occi/test#blog" }
curl -v -H 'content-type: application/json' -X POST http://malmo.lizenn.net:8080/categories/blog/ -d @blog2new3.json
* Connected to malmo.lizenn.net (95.130.12.12) port 8080 (#0)
> POST /categories/blog/ HTTP/1.1
> User-Agent: curl/7.35.0
> Host: malmo.lizenn.net:8080
> Accept: */*
> content-type: application/json
> Content-Length: 46
> 
* upload completely sent off: 46 out of 46 bytes
< HTTP/1.1 500 Internal Server Error

Using text representation:

curl -s -v -i -X POST http://malmo.lizenn.net:8080/categories/blog/ -H 'Content-Type: text/occi' -H 'Category: blog; scheme="http://example.org/occi/test#"; class="kind";'
* Connected to malmo.lizenn.net (95.130.12.12) port 8080 (#0)
> POST /categories/blog/ HTTP/1.1
> User-Agent: curl/7.35.0
> Host: malmo.lizenn.net:8080
> Accept: */*
> Content-Type: text/occi
> Category: blog; scheme="http://example.org/occi/test#"; class="kind";
> 
< HTTP/1.1 500 Internal Server Error

*MOREOVER* the last revision where it did work is:

commit 29439e6a84fca606815c218de6e907bb8ae1e731
Author: Jean Parpaillon <jean.parpaillon@free.fr>
Date:   Mon Jul 4 11:18:23 2016 +0200

    Upgrade mnesia backend and HTTP listener

**Comment by mdutoo** [comment]
Works now on local deployment since efad9024fd47c730ca7703f51322784e8fde48a7

**Comment by Romathonat** [comment]
Indeed it works on local, which is nice :).
@jeanparpaillon could you deploy it to malmo.lizenn? It is the only online erocci I can use to show how my application (OCCInterface) works. Moreover could you add the **occi-infra.xml** to malmo.lizenn? Thanks in advance

**Comment by jeanparpaillon** [comment]
Done
Can you confirm and close ?

**Comment by Romathonat** [comment]
Yes thank you !

**Comment by mdutoo** [comment]
For information, this could be reproduced easily using the OCCI Playground : go to http://occinterface.herokuapp.com, click on Known issues (on the left), then follow the instructions.

**Comment by jeanparpaillon** [comment]
@mdutoo I suppose you've messed with another issue ;) #79

**Comment by mdutoo** [comment]
Not really, the #80 issue problem was a prerequisite for #79 to be solved, so I did merely use the #79 example online in the OCCI Playground to check that POST worked again. But I've now just also tried out both above curl commands and they also work.
