### ISSUE TITLE
add occi-infra.xml to malmoz.lizenn (or somewhere accessible online)

### ISSUE THREAD

**Issue by Romathonat** [erocci/erocci#83]
In order to illustrate the possibilities of http://occinterface.herokuapp.com/, I need to access to occi-infra.xml. Indeed, the default schema with author, blog, article does not let me show one of the main feature of occinterface : navigate through links between resources. I also already have samples to populate occi-infra.xml with a simple click on the application.

I also tried to deploy erocci to heroku on my own, but it doesn't work, even with the https://github.com/erocci/heroku-buildpack-erlang that I saw you modified to make it work, but unfortunately it does not work.

**Comment by jeanparpaillon** [comment]
heroku-buildpack-erlang was a unfinished attempt. 
I've heard of many erlang apps being deployed on heroku but have not done it myself :/
