### ISSUE TITLE
Separate XML schemas

### ISSUE THREAD

**Issue by jeanparpaillon** [erocci/erocci#9]
Current occi.xsd includes XML rendering and XML extension description.
Should be separated in:
occi-core
occi-extension (import occi-core)
occi-rendering (import occi-core)

**Comment by JeanHany** [comment]
I can help for that, if you want.

**Comment by jeanparpaillon** [comment]
Hi, thanks.
Actually schemas are in erocci/apps/erocc/priv/schemas

Splitting ideas:
- core: all complexTypes but extensionType and capabilitiesType
- extension: import core, describe extensionType
- rendering: import core, describe requestType (does not exist still), can be:
  - capabilities
  - resource
  - link

**Comment by jeanparpaillon** [comment]
Schemas are now located in https://github.com/occiware/occi-schemas
